; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; Voice Assistant - Advanced Inno Setup Script
; Creates a professional Windows installer with all features

#define MyAppName "Voice Assistant BMO"
#define MyAppVersion "4.0.0"
#define MyAppPublisher "BABTIX"
#define MyAppURL "https://github.com/babtix/Agent_BMO"
#define MyAppExeName "BMO_v4.exe"
#define MyAppAssocName "Voice Assistant Session"
#define MyAppAssocExt ".vasession"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; App identification
AppId={{B4C5D6E7-F8A9-0123-4567-89ABCDEF0123}
AppName={#BMO}
AppVersion={#4}
AppVerName={#MBMO} {#4}
AppPublisher={#BY ME}
AppPublisherURL={#https://github.com/babtix/Agent_BMO}
AppSupportURL={#https://www.instagram.com/papitx0/}/issues
AppUpdatesURL={#https://github.com/babtix/Agent_BMO/releasesL}/releases
AppCopyright=Copyright (C) 2026 {#Loding...}

; Installation directories
DefaultDirName={autopf}\{#BMO}
DefaultGroupName={#BMO}
DisableProgramGroupPage=yes

; Output
OutputDir=installer_output
OutputBaseFilename=VoiceAssistant_BMO_Setup_v{#4}_x64
SetupIconFile=my_assistant_v4\icon.ico
UninstallDisplayIcon={app}\{#MyAppExeName}

; Compression
Compression=lzma2/ultra64
SolidCompression=yes
LZMAUseSeparateProcess=yes
LZMADictionarySize=1048576
LZMANumFastBytes=273

; Appearance
WizardStyle=modern
WizardImageFile=installer_banner.bmp
WizardSmallImageFile=installer_icon.bmp
DisableWelcomePage=no

; Requirements
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
MinVersion=10.0.17763

; Misc
AllowNoIcons=yes
ChangesAssociations=yes
ChangesEnvironment=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"
Name: "italian"; MessagesFile: "compiler:Languages\Italian.isl"
Name: "portuguese"; MessagesFile: "compiler:Languages\Portuguese.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"

[Types]
Name: "full"; Description: "Full installation"
Name: "compact"; Description: "Compact installation"
Name: "custom"; Description: "Custom installation"; Flags: iscustom

[Components]
Name: "main"; Description: "Main Application"; Types: full compact custom; Flags: fixed
Name: "docs"; Description: "Documentation"; Types: full
Name: "examples"; Description: "Example configurations"; Types: full
Name: "shortcuts"; Description: "Desktop and Start Menu shortcuts"; Types: full

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Components: shortcuts
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Components: shortcuts; Flags: unchecked; OnlyBelowVersion: 6.1
Name: "associate"; Description: "Associate .vasession files with {#MyAppName}"; GroupDescription: "File associations:"; Flags: unchecked

[Files]
; Main executable and dependencies
Source: "my_assistant_v4\dist\BMO_v4\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion; Components: main
Source: "my_assistant_v4\dist\BMO_v4\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: main; Excludes: "*.pyc,__pycache__"

; Configuration
Source: "my_assistant_v4\config.json"; DestDir: "{app}"; Flags: ignoreversion; Components: main
Source: "var_venv"; DestDir: "{app}"; Flags: ignoreversion onlyifdoesntexist; Components: main

; Core modules
Source: "my_assistant_v4\core\*.py"; DestDir: "{app}\core"; Flags: ignoreversion; Components: main

; Documentation
Source: "docs\*.md"; DestDir: "{app}\docs"; Flags: ignoreversion; Components: docs
Source: "README.md"; DestDir: "{app}"; Flags: ignoreversion isreadme; Components: docs
Source: "LICENSE.txt"; DestDir: "{app}"; Flags: ignoreversion; Components: docs

; Examples
Source: "my_assistant_v4\example_usage.py"; DestDir: "{app}\examples"; Flags: ignoreversion; Components: examples

; Additional files
Source: "launcher.py"; DestDir: "{app}"; Flags: ignoreversion; Components: main

[Dirs]
Name: "{app}\sessions"; Permissions: users-modify
Name: "{app}\logs"; Permissions: users-modify
Name: "{app}\temp"; Permissions: users-modify
Name: "{app}\cache"; Permissions: users-modify
Name: "{userappdata}\{#MyAppName}"; Permissions: users-modify
Name: "{userappdata}\{#MyAppName}\sessions"; Permissions: users-modify
Name: "{userappdata}\{#MyAppName}\logs"; Permissions: users-modify

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"; Comment: "Launch Voice Assistant BMO"
Name: "{group}\Documentation"; Filename: "{app}\docs"; Comment: "View documentation"
Name: "{group}\Configuration"; Filename: "{app}\config.json"; Comment: "Edit configuration"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"; Comment: "Uninstall Voice Assistant"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"; Tasks: desktopicon; Comment: "Launch Voice Assistant BMO"
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon

[Registry]
; File association
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue; Tasks: associate
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey; Tasks: associate
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"; Tasks: associate
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""; Tasks: associate
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".vasession"; ValueData: ""; Tasks: associate

; App paths
Root: HKA; Subkey: "Software\Microsoft\Windows\CurrentVersion\App Paths\{#MyAppExeName}"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Microsoft\Windows\CurrentVersion\App Paths\{#MyAppExeName}"; ValueType: string; ValueName: "Path"; ValueData: "{app}"; Flags: uninsdeletekey

; Uninstall info
Root: HKA; Subkey: "Software\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}_is1"; ValueType: string; ValueName: "DisplayIcon"; ValueData: "{app}\{#MyAppExeName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}_is1"; ValueType: string; ValueName: "HelpLink"; ValueData: "{#MyAppURL}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}_is1"; ValueType: string; ValueName: "URLInfoAbout"; ValueData: "{#MyAppURL}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}_is1"; ValueType: string; ValueName: "URLUpdateInfo"; ValueData: "{#MyAppURL}/releases"; Flags: uninsdeletekey

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
Filename: "{app}\docs\README.md"; Description: "View README"; Flags: postinstall shellexec skipifsilent unchecked

[UninstallRun]
Filename: "{cmd}"; Parameters: "/C ""taskkill /F /IM {#MyAppExeName} /T"" "; Flags: runhidden

[UninstallDelete]
Type: filesandordirs; Name: "{app}\sessions"
Type: filesandordirs; Name: "{app}\logs"
Type: filesandordirs; Name: "{app}\temp"
Type: filesandordirs; Name: "{app}\cache"
Type: filesandordirs; Name: "{app}\__pycache__"
Type: filesandordirs; Name: "{app}\core\__pycache__"
Type: filesandordirs; Name: "{userappdata}\{#MyAppName}"

[Code]
var
  ApiKeyPage: TInputQueryWizardPage;
  OllamaInfoPage: TOutputMsgWizardPage;
  ConfigPage: TInputOptionWizardPage;
  ProgressPage: TOutputProgressWizardPage;

{ Check if Ollama is installed }
function IsOllamaInstalled: Boolean;
var
  ResultCode: Integer;
begin
  Result := Exec('cmd.exe', '/C ollama --version', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) and (ResultCode = 0);
end;

{ Check if Python is installed }
function IsPythonInstalled: Boolean;
var
  ResultCode: Integer;
begin
  Result := Exec('cmd.exe', '/C python --version', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) and (ResultCode = 0);
end;

procedure InitializeWizard;
begin
  { API Key Configuration Page }
  ApiKeyPage := CreateInputQueryPage(wpSelectDir,
    'API Configuration', 
    'Configure your Groq API Key',
    'Enter your Groq API key for speech-to-text functionality.' + #13#10 + #13#10 +
    'Get your free API key from: https://console.groq.com' + #13#10 + #13#10 +
    'You can skip this and configure it later in the config.json file.');
  ApiKeyPage.Add('Groq API Key:', False);
  ApiKeyPage.Values[0] := '';
  
  { Configuration Options Page }
  ConfigPage := CreateInputOptionPage(ApiKeyPage.ID,
    'Configuration Options',
    'Choose your preferred settings',
    'Select the default configuration for Voice Assistant.',
    False, False);
  ConfigPage.Add('English (en) - Default');
  ConfigPage.Add('French (fr)');
  ConfigPage.Add('Spanish (es)');
  ConfigPage.Add('German (de)');
  ConfigPage.Values[0] := True;
  
  { Ollama Information Page }
  OllamaInfoPage := CreateOutputMsgPage(wpReady,
    'Ollama Installation Required',
    'Ollama is required for AI functionality',
    'Voice Assistant requires Ollama for the LLM (Large Language Model) functionality.' + #13#10 + #13#10 +
    'Installation steps:' + #13#10 +
    '1. Download Ollama from: https://ollama.com' + #13#10 +
    '2. Install Ollama' + #13#10 +
    '3. Open Command Prompt and run:' + #13#10 +
    '   ollama pull devstral-small-2:24b-cloud' + #13#10 +
    '4. Start Ollama service:' + #13#10 +
    '   ollama serve' + #13#10 + #13#10 +
    'Ollama Status: ' + 
    (if IsOllamaInstalled then 'Installed ✓' else 'Not Detected ✗') + #13#10 + #13#10 +
    'Click Next to continue with the installation.');
end;

function NextButtonClick(CurPageID: Integer): Boolean;
var
  ApiKey: String;
  VarVenvFile: String;
  ConfigFile: String;
  FileContent: String;
  Language: String;
begin
  Result := True;
  
  { Save API Key }
  if CurPageID = ApiKeyPage.ID then
  begin
    ApiKey := Trim(ApiKeyPage.Values[0]);
    
    if ApiKey <> '' then
    begin
      VarVenvFile := ExpandConstant('{app}\var_venv');
      FileContent := 'GROQ_API_KEY=' + ApiKey + #13#10;
      
      if not ForceDirectories(ExtractFileDir(VarVenvFile)) then
      begin
        MsgBox('Failed to create configuration directory.', mbError, MB_OK);
        Result := False;
        Exit;
      end;
      
      if not SaveStringToFile(VarVenvFile, FileContent, False) then
      begin
        MsgBox('Failed to save API key. You can configure it manually later in var_venv file.', mbInformation, MB_OK);
      end;
    end;
  end;
  
  { Save Language Configuration }
  if CurPageID = ConfigPage.ID then
  begin
    if ConfigPage.Values[0] then Language := 'en'
    else if ConfigPage.Values[1] then Language := 'fr'
    else if ConfigPage.Values[2] then Language := 'es'
    else if ConfigPage.Values[3] then Language := 'de'
    else Language := 'en';
    
    { Store language for later use in CurStepChanged }
    SetPreviousData('Language', Language);
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  Language: String;
  ConfigFile: String;
  ConfigContent: String;
begin
  if CurStep = ssPostInstall then
  begin
    { Create necessary directories }
    ForceDirectories(ExpandConstant('{app}\sessions'));
    ForceDirectories(ExpandConstant('{app}\logs'));
    ForceDirectories(ExpandConstant('{app}\temp'));
    ForceDirectories(ExpandConstant('{app}\cache'));
    ForceDirectories(ExpandConstant('{userappdata}\{#MyAppName}\sessions'));
    ForceDirectories(ExpandConstant('{userappdata}\{#MyAppName}\logs'));
    
    { Update config.json with selected language }
    Language := GetPreviousData('Language', 'en');
    ConfigFile := ExpandConstant('{app}\config.json');
    
    if FileExists(ConfigFile) then
    begin
      if LoadStringFromFile(ConfigFile, ConfigContent) then
      begin
        { Simple string replacement for language code }
        StringChangeEx(ConfigContent, '"code": "en"', '"code": "' + Language + '"', True);
        SaveStringToFile(ConfigFile, ConfigContent, False);
      end;
    end;
    
    { Create default var_venv if it doesn't exist }
    if not FileExists(ExpandConstant('{app}\var_venv')) then
    begin
      SaveStringToFile(ExpandConstant('{app}\var_venv'), 
        'GROQ_API_KEY=your_groq_api_key_here' + #13#10, False);
    end;
  end;
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
begin
  Result := '';
  
  { Check for running instances }
  if CheckForMutexes('{#MyAppName}') then
  begin
    Result := 'Voice Assistant is currently running. Please close it and try again.';
    Exit;
  end;
  
  { Warn if Ollama is not installed }
  if not IsOllamaInstalled then
  begin
    if MsgBox('Ollama is not detected on your system. Voice Assistant requires Ollama for AI functionality.' + #13#10 + #13#10 +
              'Do you want to continue with the installation?' + #13#10 + #13#10 +
              'You can install Ollama later from: https://ollama.com',
              mbConfirmation, MB_YESNO) = IDNO then
    begin
      Result := 'Installation cancelled by user.';
    end;
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  ResultCode: Integer;
begin
  if CurUninstallStep = usUninstall then
  begin
    { Kill any running instances }
    Exec('cmd.exe', '/C taskkill /F /IM {#MyAppExeName} /T', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  end;
  
  if CurUninstallStep = usPostUninstall then
  begin
    { Ask if user wants to keep configuration and sessions }
    if MsgBox('Do you want to keep your configuration files and session data?', mbConfirmation, MB_YESNO or MB_DEFBUTTON2) = IDNO then
    begin
      DelTree(ExpandConstant('{userappdata}\{#MyAppName}'), True, True, True);
    end;
  end;
end;

[Messages]
WelcomeLabel2=This will install [name/ver] on your computer.%n%nVoice Assistant BMO is an advanced AI-powered voice assistant featuring:%n%n• Wake word detection ("hi", "hello")%n• Speech-to-text (Groq Whisper API)%n• AI responses (Ollama LLM)%n• Multiple TTS engines (gTTS, Edge TTS, pyttsx3)%n• Modern PyQt6 GUI interface%n• Multi-language support (9 languages)%n• Session management%n• Conversation context%n%nIt is recommended that you close all other applications before continuing.
FinishedLabel=Setup has finished installing [name] on your computer.%n%nBefore running the application:%n1. Ensure Ollama is installed and running%n2. Configure your Groq API key if you haven't already%n3. Check the documentation in the docs folder%n%nClick Finish to exit Setup.
